migrate settings to json
Aliucord/Aliucord pull request #124
Opened 2021-10-21 17:57 UTC by mantikafasi

replaces SettingsUtils to save plugin settings into /Aliucord/settings/pluginName.json instead of sharedpreferences ,also it transfers plugin settings from shared preferences to json on plugins first launch.

2021-11-13 18:53 UTC, Vendicated requested changes

2021-11-13 19:15 UTC, Vendicated commented on Aliucord/src/main/java/com/aliucord/SettingsUtilsJSON.kt
> +                logger.error(e)
this is not resolved

2021-11-13 19:30 UTC, mantikafasi commented on Aliucord/src/main/java/com/aliucord/SettingsUtilsJSON.kt
> +                logger.error(e)
no its resolved

2021-11-13 19:34 UTC, Vendicated commented on Aliucord/src/main/java/com/aliucord/SettingsUtils.java
> +    public static void remove(String key){
add space between ) and {, add javadoc

2021-11-13 19:51 UTC, mantikafasi commented on Aliucord/src/main/java/com/aliucord/SettingsUtils.java
> +    public static void remove(String key){
I hope its ok now

2021-11-14 17:14 UTC, Vendicated approved these changes

2021-11-15 01:18 UTC, merged