Add multiform support to HTTP util class
Aliucord/Aliucord pull request #147
Opened 2021-11-14 17:06 UTC by terabyte25

2021-11-14 19:56 UTC, terabyte25 commented
there will be many a husk

2021-11-15 01:19 UTC, Vendicated commented
Please add @Nullable/@NonNull annotations and add overloads for nullable params

2021-11-16 15:47 UTC, terabyte25 commented
> Please add @Nullable/@nonnull annotations and add overloads for nullable params

Should be fixed now.

2021-11-17 02:25 UTC, Vendicated commented
Use NonNull, not NotNull. It's still missing on most methods, annotate all parameters & returns

2021-11-17 02:30 UTC, Vendicated requested changes

2021-11-17 02:30 UTC, Vendicated commented on Aliucord/src/main/java/com/aliucord/Http.java
> +            FileInputStream inputStream = new FileInputStream(uploadFile);
use try with resources instead of manually closing

2021-11-17 02:30 UTC, Vendicated commented on Aliucord/src/main/java/com/aliucord/Http.java
> +    public static class MultiBuilder {
rename to MultiPartBuilder imo

2021-11-17 02:30 UTC, Vendicated commented on Aliucord/src/main/java/com/aliucord/Http.java
> +    public static class MultiBuilder {
Seeing as this class keeps open streams, it should implement closeable and properly close all streams in the close method

2021-11-17 17:40 UTC, Vendicated approved these changes

2021-11-17 17:40 UTC, merged