feat(SupportWarn): PRD warning
Aliucord/Aliucord pull request #155
Opened 2021-11-22 02:13 UTC by DiamondMiner88

![Screenshot_20211121-181057](https://user-images.githubusercontent.com/33725716/142791025-f5b7a3a3-269d-43b9-99e6-a99bf115ab1c.png)
![Screenshot_20211121-181105](https://user-images.githubusercontent.com/33725716/142791027-97afb468-7eca-4358-9e4e-e8127c6b4dea.png)

2021-11-22 02:19 UTC, TymanWasTaken requested changes

2021-11-22 02:19 UTC, TymanWasTaken commented on Aliucord/src/main/java/com/aliucord/coreplugins/SupportWarn.kt
> +                else "PLEASE READ: This channel is not a support channel, do not ask for help."
A when statement would probably be better

2021-11-23 00:23 UTC, Vendicated commented
this will keep showing until you accept both dev and prd, no?

2021-11-28 01:43 UTC, Vendicated commented on Aliucord/src/main/java/com/aliucord/coreplugins/SupportWarn.kt
fails if channel is prd and user accepted dev channel but not prd

2021-11-28 03:08 UTC, ItzOnlyAnimal approved these changes
deosnt looks like you screwed up your logic this time so LGTM

2021-12-02 17:26 UTC, merged