Add delegation for settings
Aliucord/Aliucord pull request #160
Opened 2021-11-28 05:17 UTC by TymanWasTaken

2021-11-28 05:20 UTC, DiamondMiner88 commented on Aliucord/src/main/java/com/aliucord/SettingsUtilsJSON.kt
> +import kotlin.reflect.typeOf
Unused import probably

2021-11-28 17:56 UTC, TymanWasTaken commented
Review when

2021-11-28 18:45 UTC, mantikafasi commented
never

2021-11-29 00:30 UTC, Vendicated requested changes

2021-11-29 00:30 UTC, Vendicated commented on Aliucord/src/main/java/com/aliucord/api/SettingsAPI.java
> +        return value;
get rid of the value variable and instead return right away, then you can also drop all the else

2021-11-29 14:26 UTC, mantikafasi approved these changes

2021-12-02 11:32 UTC, Vendicated approved these changes

2021-12-02 11:32 UTC, merged