Add page to see & delete plugins that failed to load
Aliucord/Aliucord pull request #200
Opened 2022-01-20 22:01 UTC by Vendicated

2022-01-20 23:46 UTC, ItzOnlyAnimal reviewed
plugin errors still sounds weird but i have no better name lol good

2022-01-20 23:48 UTC, zt64 requested changes
Instead of hard coding IDs, maybe they could all be moved into one object that contains the IDs, would make porting versions quicker and allow plugins to reuse the ID

2022-01-20 23:48 UTC, zt64 commented on Aliucord/src/main/java/com/aliucord/widgets/FailedPluginWidget.kt
> +                text = file.name + " (${FileUtilsKt.getSizeSubtitle(file.length())})"
You will use string template

2022-01-21 00:54 UTC, zt64 commented
:trollface:

2022-01-21 00:54 UTC, ItzOnlyAnimal commented
:trollface:

2022-01-24 22:50 UTC, merged