Improved notification API
Aliucord/Aliucord pull request #22
Opened 2021-06-08 09:06 UTC by X1nto

# Summary
Replaced direct field calls with getters and setters as they're more convenient, also added documentation. Some of docs are most likely invalid so I added a `FIXME` annotation to them.

# Notes
- This **will** break the current implementation

2021-06-08 09:18 UTC, X1nto commented
> I prefer direct access as we don't really need to do anything in set/get methods here tbh.

Setters allow chaining though, which kind of gives a better syntax.

2021-06-11 18:30 UTC, Vendicated approved these changes

2021-06-12 09:05 UTC, Juby210 requested changes

2021-06-12 09:05 UTC, Juby210 commented on Aliucord/src/main/java/com/aliucord/entities/NotificationData.java
> +    //FIXME Documentation is invalid.
```suggestion
```
I don't see anything to fix here.

2021-06-12 09:05 UTC, Juby210 commented on Aliucord/src/main/java/com/aliucord/entities/NotificationData.java
> +    //FIXME Documentation is invalid.
```suggestion
```
here too

2021-06-12 10:41 UTC, Juby210 approved these changes

2021-06-12 10:42 UTC, merged